./getMotifBED.sh /ngsprojects/blsmaize/results/BLSspeller_pipeline/step5_runBlsOnHPC/output/Pac/2000up1000down/true/1degen/BEDOutput_conf95 pac_conf95
./getMotifBED.sh /ngsprojects/blsmaize/results/BLSspeller_pipeline/step5_runBlsOnHPC/output/Pac/2000up1000down/true/1degen/BEDOutput_conf90 pac_conf90
./getMotifBED.sh /ngsprojects/blsmaize/results/BLSspeller_pipeline/step5_runBlsOnHPC/output/Pac/2000up1000down/true/1degen/BEDOutput_conf85 pac_conf85
./getMotifBED.sh /ngsprojects/blsmaize/results/BLSspeller_pipeline/step5_runBlsOnHPC/output/Poa/2000up1000down/true/1degen/BEDOutput_conf95 poa_conf95
./getMotifBED.sh /ngsprojects/blsmaize/results/BLSspeller_pipeline/step5_runBlsOnHPC/output/Poa/2000up1000down/true/1degen/BEDOutput_conf90 poa_conf90
./getMotifBED.sh /ngsprojects/blsmaize/results/BLSspeller_pipeline/step5_runBlsOnHPC/output/Poa/2000up1000down/true/1degen/BEDOutput_conf85 poa_conf85
./getMotifBED.sh /ngsprojects/blsmaize/results/BLSspeller_pipeline/step5_runBlsOnHPC/output/PoaPan/2000up1000down/true/1degen/BEDOutput_conf95 poapan_conf95
./getMotifBED.sh /ngsprojects/blsmaize/results/BLSspeller_pipeline/step5_runBlsOnHPC/output/PoaPan/2000up1000down/true/1degen/BEDOutput_conf90 poapan_conf90
./getMotifBED.sh /ngsprojects/blsmaize/results/BLSspeller_pipeline/step5_runBlsOnHPC/output/PoaPan/2000up1000down/true/1degen/BEDOutput_conf85 poapan_conf85